/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IShop,
  IShopInterface,
} from "../../../contracts/interfaces/IShop";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "itemId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "itemPriceSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256[]",
        name: "itemIds",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalAmountInEth",
        type: "uint256",
      },
    ],
    name: "itemsBought",
    type: "event",
  },
];

export class IShop__factory {
  static readonly abi = _abi;
  static createInterface(): IShopInterface {
    return new utils.Interface(_abi) as IShopInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IShop {
    return new Contract(address, _abi, signerOrProvider) as IShop;
  }
}
